Enable sized delete to support pybind11 v2.4.3
This change affects the compilation with clang only. The
-fsized-deallocation flag is disabled by default on clang due to lack of
wide support from the standard libraries. Hence, the "void operator
delete ( void* ptr, std::size_t sz )" construct is disabled by default.

Meanwhile, as of version 2.4.3, pybind11 chooses the sized delete
operator whenever the C++17 standard is used for compilation. As a
result, the clang build was previously failing with errors like:

/usr/include/pybind11/pybind11.h:1008:9:
error: no matching function for call to 'operator delete'
    ::operator delete(p, s, std::align_val_t(a));

To complicate things further, the latest pybind11-dev package available
for Ubuntu is version 2.4.3. Version 2.5.0 of pybind11 has fixed the
problem by checking the "__cpp_sized_deallocation" feature macro instead
of assuming that the compiler supports sized deallocations simply
because the standard is C++17 (see pybind11 commit 759221).

Nevertheless, a fix involving an upgrade to pybind11 would imply
users/developers would need to upgrade their pybind11 versions as well,
which is not ideal. This patch instead simply enables the
sized-deallocation feature for Clang, which works with pybind11 2.4.3
and likely earlier versions.